version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    ports:
      - ${MONGODB_SERVER_PORT}:27017
    environment:
      MONGO_INITDB_DATABASE: ${DB_NAME}
      MONGO_INITDB_ROOT_USERNAME: ${DB_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
       - ./${LOCAL_DATA_STORAGE}:/data/db
       - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - ${MONGODB_EXPRESS_SERVER_PORT}:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${DB_ROOT_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DB_ROOT_PASSWORD}
